port: 8089
ssl_certificate:
ssl_certificate_key:
health_check_interval: 3
max_allowed: 100
proxy_hosts:
  - pattern: /
    host:
      - "127.0.0.1：10001"
      - "127.0.0.1：10001"
    balance_mode: round-robin